random_seed: 1244
exp_name: default
float_precision: "medium"
log_level: info

data:
  root_path: "data"
  git_url: "git@github.com:VitalyyBezuglyj/tire-check-tool.git"
  preprocessing:
    resize: [150, 150]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  val_split: 0.2

model:
  n_classes: 2


train:
  batch_size: 32
  learning_rate: 1e-3
  n_epoch: 5
  grad_accum_steps: 1
  accelerator: gpu
  devices:
    - 0
  precision: 16-mixed
  val_check_interval: 1.0
  overfit_batches: 0
  num_sanity_val_steps: 4
  full_deterministic_mode: false
  benchmark: false
  gradient_clip_val: 1.0
  profiler:
  log_every_n_steps: 25
  detect_anomaly: false

artifacts:
  base_path: outputs
  checkpoint:
    save: true
    path: checkpoints
    filename: "{epoch:02d}-{val_MulticlassF1Score:.4f}"
    monitor: val_MulticlassF1Score
    mode: max
    save_top_k: 1
    every_n_epochs: 1
    save_last: true
  logs:
    save: true
    path: logs
  metrics:
    save: true

callbacks:
  lr_monitor:
    interval: step
  model_summary:
    max_depth: 1